### ISSUE TITLE
template project shouldn't expose `info.*` properties

### ISSUE THREAD

**Issue by snicoll** [atomist-project-templates/spring-rest-service#3]
as of Spring Boot 1.4, the build plugin has a new goal `build-info`. It generates some information about the build and expose that automatically in the `info` endpoint.

The following is a pre 1.4 way of doing this:

```
info.app.artifact_id=@project.artifactId@
info.app.group_id=@project.groupId@
info.app.version=@project.version@
```

See [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-build-info)

**Comment by cdupuis** [comment]
Thanks for raising that. Will get right on that.

**Comment by cdupuis** [comment]
Fix that in master. Thanks.
