### ISSUE TITLE
Test classes use deprecated APIs

### ISSUE THREAD

**Issue by fbricon** [atomist-project-templates/spring-rest-service#5]
I generated a project via the [atomist button](https://api.atomist.com/v1/projects/generators/16271c54-e671-4be6-a30c-084aba8083ed) and the result shows a bunch of warnings in Eclipse, related to deprecated APIs:

![](http://content.screencast.com/users/fbricon/folders/Jing/media/7400ac28-88f7-4797-938b-ac677985c206/00000471.png)

**Comment by cdupuis** [comment]
Hey @fbricon, thanks for reporting this. We got this fixed yesterday per #2 and are releasing a new version of the template today.
