### ISSUE TITLE
.mvn directory missing from generated project

### ISSUE THREAD

**Issue by cdupuis** [atomist-project-templates/spring-rest-service#7]
It appears that the generated project does not contain a `.mvn` directory and therefore does not allow to run `./mvnw`.

**Comment by cdupuis** [comment]
It appears that the `spring-rest-service-3.5.2.zip` is corrupt in the production environment. Staging contains the correct version of the archive. Promoting it now and re-testing.

**Comment by cdupuis** [comment]
This is now fixed.

**Comment by janekdb** [comment]
Anyway to ensure the production environment does not include corrupt resources in the future. i.e. solve this category of problem once. Smoke tests using production resources following promotion?
